### ISSUE TITLE
Scrolling to the top of a modal is not possible if it is too lrage

### ISSUE THREAD

**Issue by Alexnortung** [themesberg/flowbite-react#622] opened 2023-02-23 09:35 UTC
**Describe the bug**
If I have a modal that is too high for the screen, then it is not possible to see the top of the modal

**To Reproduce**
Create a modal with a lot of content and see that you cannot scroll to the top

```
        <Modal>
            <Modal.Header>{label}</Modal.Header>
            <Modal.Body>
                <div>
                    {Array.from({ length: 100 }).map((_, i) => (
                        <div key={i}>Hi</div>
                    ))}
                </div>
            </Modal.Body>
        </Modal>
```

**Expected behavior**
I expected that it was possible to see the top of the modal still.

**Screenshots**
![billede](https://user-images.githubusercontent.com/1552267/220869069-beb8fc6b-da41-49d1-8569-6b91537b49be.png)

**Possible solution**
Use auto margins instead of `justify-center` and `items-center`.

**System information:**

- Device: Laptop
- Resolution: 
- OS: NixOS
- Browser: Firefox
- Version: 109.0

**Project information:**

- Tailwind: ^3.2.0
- Flowbite: 1.6.3
- Flowbite React: 0.2.1 and 0.3.7
- Type: Nextjs

**Comment by multiwebinc** [comment] 2023-02-23 16:27
Duplicate of #600

**Closed** 2023-02-23 18:02 UTC
