### ISSUE TITLE
Modal backdrop does not cover full screen when viewport size is small

### ISSUE THREAD

**Issue by zammitjohn** [themesberg/flowbite-react#520] opened 2023-01-06 11:50 UTC
**Describe the bug**
Modal backdrop does not cover full screen when viewport size is small

**To Reproduce**

1. Open https://flowbite-react.com/modal
2. Toggle modal
3. Resize window size width to < 767 px

**Expected behaviour**
Backdrop should always cover full screen

**Screenshots**
![Screenshot 2023-01-06 124911](https://user-images.githubusercontent.com/64637336/211006858-063a6f50-c1e8-41b7-803f-e363ab83916b.png)

**Comment by mortezasabihi** [comment] 2023-01-11 11:24
The bug is caused by the **core flowbite** found at this link: https://github.com/themesberg/flowbite/blob/e8c6490bd1893f467f347c41dc5147e6648b9dcb/plugin.js#L455.
The purpose of this line modal: 'calc(100% - 2rem)' is unclear, could you provide some context @zoltanszogyenyi?

**Comment by rluders** [comment] 2023-01-11 12:24
Well, we basically don't use any flowbite core javascript in the react-flowbite... So...

**Comment by zoltanszogyenyi** [comment] 2023-01-11 12:29
Hey peeps,

We use that to enable vertical scroll when the body content of the modal exceeds the viewport of a smaller device - it's probably not the best solution and we'll revisit this when overhauling the modal component with more options and animations.

Here's an example without the `h-modal` tag on mobile devices:

<img width="1015" alt="Screenshot 2023-01-11 at 14 27 22" src="https://user-images.githubusercontent.com/8052108/211806271-3f92bda8-8f8b-4227-8310-94401f8cff7b.png">

As you can see, we add this to make sure that the modal takes up the height of the viewport minus `2rem` to add some space between the modal and the edge of the screen.

I believe we will find a better solution when we'll update the modal component.

**Comment by rluders** [comment] 2023-01-12 08:42
@zoltanszogyenyi let me know when if got fixed at the flowbite core, so we can apply the fix here as well. :)

**Comment by zoltanszogyenyi** [comment] 2023-03-04 08:47
Hey @rluders @tulup-conner,

I've checked the behaviour of the modal on Flowbite React and we might have to generate a `<div>` that will be prepended to the last tag of the `</body>` element and apply these basic classes:

`bg-gray-900 bg-opacity-50 dark:bg-opacity-80 fixed inset-0 z-40`

The gap is there because the modal might have more content inside of it so we want to enable scroll on mobile devices so the users can navigate through all of the content available inside of the modal.

We also have the `h-modal` class which I think that we could exchange with `h-[calc(100vh-2rem)]`.

This is probably the best solution especially if we're going to allow users to close the modal when clicking outside of the modal, I believe that the backdrop should be a separate HTML tag and it shouldn't be the modal itself, unless there are valid accessibility issues though I couldn't think of one.

Cheers,
Zoltan

**Closed** 2023-07-25 19:25 UTC
Labels: needs info
