### ISSUE TITLE
Can't Pass Ref to Sidebar Component (due to dynamic nature)

### ISSUE THREAD

**Issue by ogheneovo12** [themesberg/flowbite-react#935] opened 2023-08-26 03:39 UTC
- [ ] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [ ] I have tested the latest version

## Current behavior

Passing Ref to the Sidebar container isn't possible due to the Sidebar using a dynamic Container Component, ref are meant to be passed to Dom Element and not container

## Expected behavior
Should be able to pass ref to sidebar (applied to nav wrapper)

Describe what you expected to happen.
i Should be able to pass ref to sidebar base container, without any errors or warning

## Context

What are you trying to accomplish? Does this only happen on a specific browser, screen size, or operating system?
I Wanted to be able to detect a click outside the sidebar, so as to collapse it, when ever there's an interaction outside (event.trigger doesn't match the sidebar), in-order to do this i need to get a reference to the sidebar nav (or related container), since the container is dynamic and rendered as a component react throws the  below error  

```
: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

```

If possible, provide a live example URL, screenshot, video, or a repository with the minimal reproduction of the issue.
![Screenshot (1066)](https://github.com/themesberg/flowbite-react/assets/49083654/de7ad3aa-798a-48e2-898e-adf404dcadb6)

**Comment by rluders** [comment] 2023-09-29 08:13
I would love to have a minimal reproducible scenario here.

**Comment by tulup-conner** [comment] 2024-01-01 20:51
Closing since we haven't gotten a reproduction. FYI, you can also accomplish this in a few different ways by listening for click events outside the `<Sidebar>`.

**Closed by tulup-conner** 2024-01-01 20:51 UTC
Labels: needs info
