### ISSUE TITLE
Button as a link error

### ISSUE THREAD

**Issue by mnakhli** [themesberg/flowbite-react#1107] opened 2023-11-05 12:46 UTC
When I use the button as a link, I get an error:
<img width="1583" alt="Screenshot 1402-08-14 at 16 13 55" src="https://github.com/themesberg/flowbite-react/assets/21153535/bb69053f-ca71-440f-9424-3c35483b0a3c">

I proceeded exactly according to [the documentation](https://www.flowbite-react.com/docs/components/button#override-button-base-component).

**Comment by jonnyruffles** [comment] 2023-12-13 23:12
@rluders I have the same issue using Webstorm as my IDE. Here's some information:

![image](https://github.com/themesberg/flowbite-react/assets/136707592/eb9e3a7d-e1fc-453c-8f35-dcdf95c150a5)

```
  "dependencies": {
    < ... >
    "flowbite": "^2.2.0",
    "flowbite-react": "0.7.2",
  }
```

```
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "eslint": "^8",
    "eslint-config-next": "14.0.4",
    "eslint-config-prettier": "^9.1.0",
    "postcss": "^8",
    "prettier": "^3.1.1",
    "prisma": "^5.7.0",
    "tailwindcss": "^3.3.0",
    "ts-node": "^10.9.2",
    "typescript": "^5"
  }
```

**Comment by jonnyruffles** [comment] 2023-12-13 23:14
Duplicate of #1002

**Closed** 2023-12-14 04:22 UTC
Labels: needs info
