### ISSUE TITLE
Add slideTo to Carousel settings

### ISSUE THREAD

**Issue by maykelesser** [themesberg/flowbite-react#1192] opened 2023-12-15 22:04 UTC
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Summary

Just like we have in the default Flowbite (https://flowbite.com/docs/components/carousel/#methods), i'd like to set the current slide in a event. I don't know how to achieve it using the flowbite-react Carousel.

## Context
I'm trying to sync two carousels to set same indexes at same time. One is in a modal, and other is outside.

**Comment by tulup-conner** [comment] 2023-12-17 09:30
Thank you! You can do this manually by clicking the desired indicator but, yeah, there's no way to set it programmatically. That could be useful and, like you point out, it's in vanilla so we should have it.

**Comment by tulup-conner** [comment] 2024-01-01 23:30
This is a duplicate of #1094, though

**Closed by tulup-conner** 2024-01-01 23:30 UTC
Labels: :rocket: enhancement, good first issue
