### ISSUE TITLE
Dropdown dismiss on click only works the first time

### ISSUE THREAD

**Issue by stuart-williams** [themesberg/flowbite-react#793] opened 2023-06-03 10:25 UTC
**Describe the bug**
Dropdown dismiss on click only works the first time the dropdown menu is opened

**To Reproduce**

1. Trigger drop down
2. Clicking an item dismisses the menu as expected
3. Trigger dropdown a second time
4. Clicking an item does not dismiss the menu

**Expected behavior**
Clicking a dropdown menu item dismisses the menu consistently

**Screenshots**

https://github.com/themesberg/flowbite-react/assets/2526507/28decfc7-ebec-40b5-b93b-5e4b2a71683c

**System information:**

- Device: Mac
- Resolution:
- OS: Monterey
- Browser: Chrome
- Version: 114.0.5735.90

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

**Comment by nbsp1221** [comment] 2023-06-05 08:06
Same problem for me. I think the cause of this issue is in `Dropdown.tsx`.

https://github.com/themesberg/flowbite-react/blob/35e7f5b79febad8aa40eaf5eb9be9b030816e2f4/src/components/Dropdown/Dropdown.tsx#L92-L95

https://github.com/themesberg/flowbite-react/blob/35e7f5b79febad8aa40eaf5eb9be9b030816e2f4/src/components/Dropdown/Dropdown.tsx#L63

In order to dismiss the menu, `setCloseRequestKey` should be called with random `id` value. However, `useId` hook does not return a random value every time you click items.

![image](https://github.com/themesberg/flowbite-react/assets/50603255/636afb7e-3374-4fe7-9290-c100b42d5240)

When I replaced the `useId` hook with a random string generator as shown above, it worked fine.

I hope this information helps to resolve the issue.

**Comment by tulup-conner** [comment] 2023-06-06 23:07
@nbsp1221 Thank you for catching that! I specifically undid that change and did not realize this is a thing that happens. That is my bad. 

If someone wants to make a PR - please do! It should be as simple as doing exactly what @nbsp1221 did here, or something simpler to understand like, `Math.random().toString(8)`.

My guess is that `useId` is supposed to work with React Server Components, but we're forcing `use client` for all of our components and breaking that behavior. That is likely the core issue, which we can and will resolve in the future, at which point we can use `useId` for its intended purpose here. See the second "pitfall" noted in https://react.dev/reference/react/useId#why-is-useid-better-than-an-incrementing-counter

**Comment by tulup-conner** [comment] 2023-06-07 00:32
This is a duplicate of #625 but I didn't realize that and the proposed solution  provided here is great so we can keep the discussion here.

**Comment by mansgori** [comment] 2023-06-08 03:33
@tulup-conner Hi, I understand the problem. I want to working on this problem. can you assign to me?

**Comment by rluders** [comment] 2023-07-03 19:01
@nigellima are you working on this one? I noticed that you created a commit with a reference to this task. :)

**Comment by nigellima** [comment] 2023-07-03 19:07
> @nigellima are you working on this one? I noticed that you created a commit with a reference to this task. :)

Hey, yes. It still in my local environment. But that commit in specific I will drop it, because I'm actually working on the #648 , which will solve this and some other issues related to the Dropdown component

**Comment by rluders** [comment] 2023-07-03 19:17
@nigellima all right. Thanks, I'll be waiting for your the PR. Valeu, jovem. :)

**Closed** 2023-07-06 16:30 UTC
