### ISSUE TITLE
Modal incorrect vertical position on screens below md. 

### ISSUE THREAD

**Issue by timthedev07** [themesberg/flowbite-react#1169] opened 2023-12-03 21:06 UTC
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Import and use the modal component in React.js
2. Set position prop to "center"
3. Reduce window width and observe that the modal always appears at the top of the screen.

## Current behavior

The `position="center"` prop doesn't center the modal vertically on smaller screens of sizes below `md`.

## Expected behavior

Expected the modal to be centered vertically too.

## Context

<img width="1470" alt="截屏2023-12-03 22 07 50" src="https://github.com/themesberg/flowbite-react/assets/65774333/b99b63e6-6f4f-44cd-9e20-0cfc5f1c5911">

**Comment by tulup-conner** [comment] 2024-01-01 19:53
Thank you, yeah, this has been an issue for a while and needs to be addressed.

**Comment by tulup-conner** [comment] 2024-01-01 19:54
This is technically a duplicate of #1083 though

**Closed by tulup-conner** 2024-01-01 19:54 UTC
Labels: :bug: bug, confirmed

**Comment by banana970** [comment] 2024-01-21 05:38
Please solve it quickly. The modal cannot be placed. And can the modal height be set automatically? I want to give the style myself, but it doesn't apply.

**Comment by teknosains** [comment] 2024-10-04 15:36
> Please solve it quickly. The modal cannot be placed. And can the modal height be set automatically? I want to give the style myself, but it doesn't apply.

Here is how to fix the modal alignment issue on Small screen

```
 <Modal 
    show={openModal} 
    onClose={() => setOpenModal(false)} 
    position="center"
    theme={{
      content: {
        base: 'bg-transparent w-3/4'
      }
    }}
 >
```
yaps that's right, just by adding ```theme``` prop
