### ISSUE TITLE
Error when using flowbite-react in Next.js: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by osilkin98** [themesberg/flowbite-react#573] opened 2023-01-31 13:24 UTC
**Describe the bug**
When rendering a page with a modal, if the page wasn't navigated to from a previous context, e.g. using Link from next/link, then a huge stack trace about `document` being undefined appears from the Modal component.

**To Reproduce**

Use the Modal in any Next.js 13 page.

**Expected behavior**
The modal should open and the page should load normally.

**Screenshots**

**System information:**

- Device: Desktop PC
- Resolution: 1440p
- OS: Windows 10
- Browser: Firefox
- Version: Windows 10

**Project information:**

- Tailwind: 3.2.0
- Flowbite: 1.6.3
- Flowbite React: 0.3.8
- Type: Next.js

**Additional context**
Error trace:
```
 1 of 1 unhandled error
Server Error

ReferenceError: document is not defined
This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
ModalComponent
file:/home/oleg/case0/node_modules/.pnpm/flowbite-react@0.3.8_m4gtgwxodlxragupfwvq4tjnru/node_modules/flowbite-react/lib/cjs/components/Modal/Modal.js (17:50)
renderWithHooks
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5658:16)
renderIndeterminateComponent
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5731:15)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5946:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderChildrenArray
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6211:7)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6141:7)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderNode
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6259:12)
renderHostElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5642:3)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5952:5)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderContextProvider
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5920:3)
renderElement
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6017:11)
renderNodeDestructiveImpl
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6104:11)
renderNodeDestructive
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (6076:14)
renderIndeterminateComponent
file:/home/oleg/case0/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.development.js (5785:7)
```

**Comment by zhaodong-wang** [comment] 2023-02-01 10:24
Same issue here

**Comment by rluders** [comment] 2023-02-01 11:58
It seems related to #123 but not the same issue. Maybe as @zhaodong-wang said we need to check for `document`. I'm not familiar with NextJS.

Can someone explain why it is working [here](https://github.com/tulupinc/flowbite-next-starter) in the NextJS sample project? 🤔

**Comment by cadu0xcarbon** [comment] 2023-02-02 02:46
Can confirm this is happening here too, since last release 0.3.8

@rluders its because [flowbite-next-starter](https://github.com/tulupinc/flowbite-next-starter) is actually running on 0.3.7, if you see here: https://github.com/tulupinc/flowbite-next-starter/blob/main/yarn.lock#L1612

If you clone the repo, delete yarn.lock and then `yarn install` it will install the latest flowbite-react which is 0.3.8. Then the error mentioned in this issue occurs from `yarn build && yarn start`

**Comment by rluders** [comment] 2023-02-02 07:19
Thank you, @cadu0xcarbon. Well, let's wait to see if the refactoring will solve this issue as well.

**Comment by cesarvarela** [comment] 2023-03-03 21:48
This is still broken on 0.4.1

**Comment by tulup-conner** [comment] 2023-03-04 02:35
I don't have this issue on the new Next.js branch so I expect it to be resolved soon. Will follow up.

**Comment by osilkin98** [comment] 2023-03-09 03:23
@tulup-conner I'm still having this issue on Flowbite v0.4.2

**Comment by nsoubelet** [comment] 2023-03-14 15:54
Hi, also happening to me using the following versions:
```
"flowbite": "^1.6.3",
"flowbite-react": "^0.4.2",
"next": "13.2.4",
"react": "18.2.0"
```
@osilkin98 Have you found a workaround? Since I am not sure when the fix will be released.

**Comment by emilshr** [comment] 2023-03-14 16:26
Upvoting this issue. I'm getting the same errors with the following versions
<img width="311" alt="image" src="https://user-images.githubusercontent.com/83577747/225072153-d9d45363-afe8-41da-ab5a-5a01c1858b4c.png">

**Comment by chenaaron3** [comment] 2023-03-19 05:24
Getting same problem with following versions
```
    "flowbite": "^1.6.4",
    "flowbite-react": "^0.4.2",
    "next": "^13.2.1",
    "react": "18.2.0",
```

**Comment by bmatzner** [comment] 2023-03-20 17:04
Happens in the flowbite-remix-starter as well, when using flowbite-react > 0.3.7.

**Comment by osilkin98** [comment] 2023-03-20 17:13
@nsoubelet My workaround has been to not use the flowbite-react component and instead convert the HTML they provide on flowbite.com into a Modal that I display on my page like this:

```tsx
const useModal = () =>{
  // implementation
  return { modalContent, isOpen, setOpen, closeModal }
}

// somewhere later
const MyPage = () => {
  const { modalContent, isOpen, openModal, closeModal } = useModal();
  

  const handleAlert = () => {
    openModal(
      <div>
          {/* content from flowbite */}
          <button onClick={closeModal}>Close</button>
       </div>
    );
  }
  

  return (
    <>
      <MainPageComponents onAlertClick={handleAlert} />
      {isOpen && modalContent}
    </>
} 

```

**Comment by osilkin98** [comment] 2023-03-22 19:20
What is the ETA on this issue being fixed? At the moment it is blocking builds in Next.js:
```
@plicanta/nextjs:build: Error occurred prerendering page "/settings". Read more: https://nextjs.org/docs/messages/prerender-error
@plicanta/nextjs:build: ReferenceError: document is not defined
@plicanta/nextjs:build:     at ModalComponent (/home/oleg/case0/node_modules/flowbite-react/lib/cjs/components/Modal/Modal.js:26:32)
@plicanta/nextjs:build:     at Wc (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
@plicanta/nextjs:build:     at Zc (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
@plicanta/nextjs:build:     at Z (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@plicanta/nextjs:build:     at Zc (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:481)
@plicanta/nextjs:build:     at Z (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
@plicanta/nextjs:build:     at $c (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
@plicanta/nextjs:build:     at bd (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
@plicanta/nextjs:build:     at Z (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
@plicanta/nextjs:build:     at $c (/home/oleg/case0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
```

**Comment by frontalicious-martijn** [comment] 2023-03-24 21:53
I get the same error in Remix. The server rendering does not have a `document` so the Modal component needs some tweaks for that.

**Comment by tulup-conner** [comment] 2023-03-26 23:00
I encourage anyone who is having this issue to contribute a PR that solves it. Unfortunately I haven't had time this month to get to this and, in general the Modal needs a lot of work to provide a good developer experience. See #568. I can't provide ETAs on anything.

**Comment by mattg66** [comment] 2023-03-27 19:02
Same problem here as others, not sure how to fix, have tried everything. I'm guessing its something to do with these lines in Modal.js:
`if (!containerRef.current) {
        containerRef.current = document.createElement('div');
    }
    // If the current value of the ref is not already a child of the root element,
    // append it or replace its parent.
    if (containerRef.current.parentNode !== root && (0, window_exists_1.default)()) {
        root = root || document.body;
        root.appendChild(containerRef.current);
    }`

**Comment by AlfieJones** [comment] 2023-03-27 20:33
I've opened up a fix here https://github.com/themesberg/flowbite-react/pull/677

In the mean time, I've published the changes under"@alfiejones/flowbite-react"

**Comment by tulup-conner** [comment] 2023-03-28 00:25
Sweet. I left a comment on #677. This is clearly impacting a lot of people so I'm happy to push a release out ASAP even with just this one fix.

**Closed** 2023-03-29 13:28 UTC
Labels: bug, confirmed, nextjs

**Comment by hritikb27** [comment] 2023-05-31 09:12
Is this still not fixed? I am facing same issue in Nextjs

**Comment by ootsun** [comment] 2023-05-31 10:08
Yes, it was fixed in https://github.com/themesberg/flowbite-react/releases/tag/v0.4.3

**Comment by Mgazul** [comment] 2024-10-05 09:40
```
"flowbite-react": "^0.10.2",
"next": "14.2.14",
```

The error occurs again

```
 ⨯ ReferenceError: document is not defined
    at Object.<anonymous> (D:\GitHub\mohistmc-frontend-cn\node_modules\flowbite-datepicker\dist\main.cjs.js:595:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (D:\GitHub\mohistmc-frontend-cn\node_modules\next\dist\server\require-hook.js:65:28)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (D:\GitHub\mohistmc-frontend-cn\node_modules\flowbite\lib\cjs\components\datepicker\index.js:16:29)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at mod.require (D:\GitHub\mohistmc-frontend-cn\node_modules\next\dist\server\require-hook.js:65:28)

```

After returning to ```"flowbite-react": "^0.8.0"```, the problem no longer occurs

**Comment by SutuSebastian** [comment] 2024-10-05 09:52
> ```
> "flowbite-react": "^0.10.2",
> "next": "14.2.14",
> ```
> 
> The error occurs again
> 
> ```
>  ⨯ ReferenceError: document is not defined
>     at Object.<anonymous> (D:\GitHub\mohistmc-frontend-cn\node_modules\flowbite-datepicker\dist\main.cjs.js:595:13)
>     at Module._compile (node:internal/modules/cjs/loader:1469:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
>     at Module.load (node:internal/modules/cjs/loader:1288:32)
>     at Module._load (node:internal/modules/cjs/loader:1104:12)
>     at Module.require (node:internal/modules/cjs/loader:1311:19)
>     at mod.require (D:\GitHub\mohistmc-frontend-cn\node_modules\next\dist\server\require-hook.js:65:28)
>     at require (node:internal/modules/helpers:179:18)
>     at Object.<anonymous> (D:\GitHub\mohistmc-frontend-cn\node_modules\flowbite\lib\cjs\components\datepicker\index.js:16:29)
>     at Module._compile (node:internal/modules/cjs/loader:1469:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
>     at Module.load (node:internal/modules/cjs/loader:1288:32)
>     at Module._load (node:internal/modules/cjs/loader:1104:12)
>     at Module.require (node:internal/modules/cjs/loader:1311:19)
>     at mod.require (D:\GitHub\mohistmc-frontend-cn\node_modules\next\dist\server\require-hook.js:65:28)
> ```
> 
> After returning to `"flowbite-react": "^0.8.0"`, the problem no longer occurs

Make sure to `rm -rf node_modules` and do a fresh package install, I just tested this and it works perfectly fine.

**Comment by Mgazul** [comment] 2024-10-05 10:04
> > ```
> > "flowbite-react": "^0.10.2",
> > "next": "14.2.14",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The error occurs again
> > ```
> >  ⨯ ReferenceError: document is not defined
> >     at Object.<anonymous> (D:\GitHub\mohistmc-frontend-cn\node_modules\flowbite-datepicker\dist\main.cjs.js:595:13)
> >     at Module._compile (node:internal/modules/cjs/loader:1469:14)
> >     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
> >     at Module.load (node:internal/modules/cjs/loader:1288:32)
> >     at Module._load (node:internal/modules/cjs/loader:1104:12)
> >     at Module.require (node:internal/modules/cjs/loader:1311:19)
> >     at mod.require (D:\GitHub\mohistmc-frontend-cn\node_modules\next\dist\server\require-hook.js:65:28)
> >     at require (node:internal/modules/helpers:179:18)
> >     at Object.<anonymous> (D:\GitHub\mohistmc-frontend-cn\node_modules\flowbite\lib\cjs\components\datepicker\index.js:16:29)
> >     at Module._compile (node:internal/modules/cjs/loader:1469:14)
> >     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
> >     at Module.load (node:internal/modules/cjs/loader:1288:32)
> >     at Module._load (node:internal/modules/cjs/loader:1104:12)
> >     at Module.require (node:internal/modules/cjs/loader:1311:19)
> >     at mod.require (D:\GitHub\mohistmc-frontend-cn\node_modules\next\dist\server\require-hook.js:65:28)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After returning to , the problem no longer occurs`"flowbite-react": "^0.8.0"`
> 
> Make sure to and do a fresh package install, I just tested this and it works perfectly fine.`rm -rf node_modules`

I have tried it many times, but still no solution.

**Comment by SutuSebastian** [comment] 2024-10-05 10:25
@Mgazul if u could provide more context, or even better a reproduce snippet using https://codesandbox.io/ or https://stackblitz.com/ (or others)

**Comment by Mgazul** [comment] 2024-10-05 10:29
> @Mgazul if u could provide more context, or even better a reproduce snippet using https://codesandbox.io/ or https://stackblitz.com/ (or others)

https://github.com/MohistMC/mohistmc-frontend-cn
This is my project, you only need to update the corresponding version to reproduce the error

**Comment by SutuSebastian** [comment] 2024-10-05 10:53
> > @Mgazul if u could provide more context, or even better a reproduce snippet using https://codesandbox.io/ or https://stackblitz.com/ (or others)
> 
> https://github.com/MohistMC/mohistmc-frontend-cn This is my project, you only need to update the corresponding version to reproduce the error

The main issue is that u are importing `flowbite` and `flowbite-react` in `src/pages/_app.tsx`, which is wrong in many ways:
- `flowbite` and `flowbite-react` don't need to be imported top level, at all
- `flowbite` package is only used and installed as a `dependency` in `flowbite-react` because we need to extend the main tailwindcss plugin (this will be gone in the future versions, but for now that's how it is)
- the error is thrown because there have been some changes in `flowbite-datepicker` package that try to access DOM API's and this fails during SSR
  - importing `flowbite` top level in any framework of choice that does SSR will fail with the same error, unless treated accordingly so that it only imports on the client, and/or its being triggered/initialized on the client

Now, I'm not sure the reason behind importing both `flowbite` and `flowbite-react` top level, maybe it was because u wanted to use components from https://flowbite.com/  and needed the required JS for interactivity and business logic, idk!
But if this is the case, there's a better approach and I can describe it.

**Comment by SutuSebastian** [comment] 2024-10-05 11:12
@Mgazul now I played around more with ur app, it seems like u do actually use vanilla components from https://flowbite.com/, for example in the navbar->dropdowns, in that case, please add the following snippet in `src/pages/_app.tsx` to enable JS for vanilla components:

```tsx
useEffect(() => {
    import('flowbite').then(({ initFlowbite }) => initFlowbite())
}, [])
```
