### ISSUE TITLE
The text hangs on it icon in input field with icon

### ISSUE THREAD

**Issue by bNc326** [themesberg/flowbite-react#828] opened 2023-06-26 18:09 UTC
**Describe the bug**

When i would like TextInput componenet with icon, then text hangs on it icon! 

**Screenshots**

![Screenshot 2023-06-26 200638](https://github.com/themesberg/flowbite-react/assets/107045445/82e2b298-ed98-456a-b5d0-e170966c6133)

![Screenshot 2023-06-26 200137](https://github.com/themesberg/flowbite-react/assets/107045445/168dfc4e-c33f-4491-bdd9-b64d3ace34a5)

steps:
1. add icon={exmaple} prop to TextInput component
2. add any value
3. see bug

**Project information:**

- Tailwind: 3.3.2
- Flowbite: 1.6.6
- Flowbite React: 0.4.9

**Comment by rluders** [comment] 2023-06-27 07:13
The issue is visible in the documentation as well (https://www.flowbite-react.com/docs/components/forms) it should be very easy to push a fix for this one. I'm not sure if this is happening 'cause of the introduction of `twMerge` (#800), but if I have to guess I would say that it is possible.

Anyway, if this is the case, what needs to be done is to check the order of the classes to make sure that `twMerge` isn't removing any class. 

So, it is probably happening here:

https://github.com/themesberg/flowbite-react/blob/ab59ada4d9dd39d4b53df83bd18f6a2b28648669/src/components/TextInput/TextInput.tsx#L87-L94

And the changes need to be done somewhere around here:

https://github.com/themesberg/flowbite-react/blob/ab59ada4d9dd39d4b53df83bd18f6a2b28648669/src/components/TextInput/theme.ts#L35

https://github.com/themesberg/flowbite-react/blob/ab59ada4d9dd39d4b53df83bd18f6a2b28648669/src/components/TextInput/theme.ts#L39

**Comment by nigellima** [comment] 2023-06-27 17:46
HI @rluders @bNc326 
I had noticed this issue too on the newest version. I have done I fix in my fork and if you want it I can submit a PR.

But in case @bNc326 would like to submit it: The fix was basically changing the ordering of the sizes classes as rluders suggested. Also, the classes for the rightIcon were missing too:

```jsx
<input
  className={twMerge(
    theme.field.input.base,
    theme.field.input.colors[color],
    theme.field.input.sizes[sizing],
    theme.field.input.withIcon[Icon ? 'on' : 'off'],
    theme.field.input.withRightIcon[RightIcon ? 'on' : 'off'],
    theme.field.input.withAddon[addon ? 'on' : 'off'],
    theme.field.input.withShadow[shadow ? 'on' : 'off'],
  )}
  {...props}
  ref={ref}
/>
```

**Closed** 2023-06-29 12:42 UTC
Labels: bug, help wanted, good first issue, confirmed
