### ISSUE TITLE
How to use flowbite-react in React Server Components

### ISSUE THREAD

**Issue by focux** [themesberg/flowbite-react#448] opened 2022-11-30 23:48 UTC
**Describe the bug**
There are some static components that _should_ work on server components (Next.js 13), for instance, the avatar component—and many others—but for some reason is throwing the error below that seems to be coming from `floating-ui`:

```
You're importing a component that needs flushSync. It only works in a Client Component but none of its parents are marked with "use client", so they're Server Components by default.

   ,----
 5 | import { createPortal, flushSync } from 'react-dom';
   :                        ^^^^^^^^^
   `----

Maybe one of these should be marked as a client entry with "use client":
  ../../node_modules/.pnpm/@floating-ui+react-dom-interactions@0.9.3_2zx2umvpluuhvlq44va5bta2da/node_modules/@floating-ui/react-dom-interactions/dist/floating-ui.react-dom-interactions.mjs
```

**To Reproduce**

1. Create a Next.js 13 project—or any other framework that uses server components.
2. Render an Avatar component on a server component page.
4. See the error

**Expected behavior**
Static components should work on server components

**System information:**

- Device: Macbook
- OS: Mac OS
- Browser: Chrome
- Version: Latest

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: Next.js 13

**Comment by rluders** [comment] 2022-12-01 07:37
@focux could you please update your `flowbite-react` and check if the issue still happening?

**Comment by focux** [comment] 2022-12-01 12:41
Updated to the latest version (0.3.5) and still happening.

**Comment by rluders** [comment] 2023-01-20 15:03
Well, it is hard to say. I know that ppl for other libraries, like material-ui, also are having the same issue. I'm not that much into react/nextjs universe, so... by now, the best thing is to pay attention to other libs moves and wait 'till someone interested in work on this one shows up.

**Comment by mpereira** [comment] 2023-01-24 15:30
I'm seeing the same on flowbite-react 0.3.7. Ideally all flowbite-react component parts that require [interactivity/state/hooks](https://beta.nextjs.org/docs/rendering/server-and-client-components#when-to-use-server-vs-client-components) would be [moved to leaves of the render tree](https://beta.nextjs.org/docs/rendering/server-and-client-components#moving-client-components-to-the-leaves), so that server component rendering could be taken advantage of.

For now I'm using the [workaround](https://beta.nextjs.org/docs/rendering/server-and-client-components#third-party-packages) shown in the Next.js 13 docs, which makes a root flowbite-react component (e.g., `Avatar`) a client component entirely, which doesn't take advantage of server component rendering:

`src/js/components/third_party/flowbite-react/Avatar.js`:
```js
'use client';

import { Avatar } from 'flowbite-react';

export default Avatar;
```

---

Original issue for reference:
```
 2 | export * from '@floating-ui/react-dom';
 3 | import * as React from 'react';
 4 | import { useLayoutEffect, useEffect, useRef } from 'react';
 5 | import { createPortal, flushSync } from 'react-dom';
   :                        ^^^^^^^^^
 6 | import { hideOthers } from 'aria-hidden';
 7 | 
 8 | var index = typeof document !== 'undefined' ? useLayoutEffect : useEffect;
   `----

Maybe one of these should be marked as a client entry with "use client":
  node_modules/@floating-ui/react-dom-interactions/dist/floating-ui.react-dom-interactions.mjs
  node_modules/flowbite-react/lib/cjs/components/Floating/Floating.js
  node_modules/flowbite-react/lib/cjs/components/Floating/index.js
  node_modules/flowbite-react/lib/cjs/components/Dropdown/Dropdown.js
  node_modules/flowbite-react/lib/cjs/components/Dropdown/index.js
  node_modules/flowbite-react/lib/cjs/components/index.js
  node_modules/flowbite-react/lib/cjs/index.js
  src/js/components/UserPictureAndUsername.js
  src/js/components/StoryListItem.js
  app/stories/page.js
```

**Comment by zoltanszogyenyi** [comment] 2023-01-24 17:15
May I also add my 2 cents - the general consensus in the React / Next.js / Remix ecosystem is that the path forward are server rendered components, meaning we should really take into account providing official support or at least _documenting a workaround_ as people using Flowbite React and choosing to use SSC are going to have trouble using the library from the get-go.

**Comment by tulup-conner** [comment] 2023-03-04 00:12
Let's pivot this issue to focus on writing documentation on how to implement flowbite-react in React Server Components. I already have on the flowbite-next-starter, so I know it works correctly, you just need to recognize that these components in many cases depend on client-side state to function.

**Comment by rootical** [comment] 2023-03-04 08:29
@tulup-conner but currently all components will break (like even eg buttons) during SSR. What is to document, like adding `'use client';` everywhere in next.js for example? 
I didn't dive deep but looks like the issue is theme awareness implementation. Why not to try to at least make it isomorphic?
So far I am just creating my own components based on flowbite css - because this library won't help in the case of SSR.

**Comment by tulup-conner** [comment] 2023-03-04 08:53
You can't conditionally call a hook, so I'm not sure how we could make the theme optional, ergo, allow components to be fully server side rendered without JS.

People need to be able to systematically customize the design system, and the cost of that is JS in the client.

My Remix and Vite projects work out of the box with this library with JS enabled. The problem only arises when you try to load the page without JS, and there are no classes applied. Obviously, that sucks too. I don't really know what the step forward is.

**Comment by Ponjimon** [comment] 2023-03-27 11:13
> People need to be able to systematically customize the design system, and the cost of that is JS in the client, or at least seems to be. I may just be unaware of another option.

I just recently discovered Flowbite and Flowbite React and it being a Tailwind based library, I assumed to change the theme, I could just change the Tailwind config. If that was a possibility, there would not be any need for JS to change the theme.

Especially since Flowbite React already requires the use of the `flowbite/plugin`. There could be the default styles as they are right now but with the possibility to extend them using the plugin in the same way, as Tailwind would extend its own styles inside the `theme.extend` object. I don't have access to the Discord discussion mentioned above, so I apologize if this is something that has already been discussed.

**Comment by tulup-conner** [comment] 2023-03-28 00:37
We have discussed it before for sure but that's quite alright! It's another option on the menu for sure, and something I wanted when I first started using the library as well. I haven't toyed with it with actual code but in theory there's no reason we can't. I've read the config file in personal projects >2 years ago and it worked well enough. I imagine it only works better now.

In an ideal world, I'd like to add an optional build step that takes your tailwind config and generates flowbite-react components without `useTheme` at all. Then you wouldn't have to compromise on progressive enhancement. Tailwind CSS users already have to run Tailwind CSS anyway. That might be something a Tailwind CSS plugin can do, but I don't know anything about how they work, honestly.

**Comment by MichaelReaNZ** [comment] 2023-05-08 23:45
This issue has me steering away from flowbite unfortunately.

**Comment by zoltanszogyenyi** [comment] 2023-05-09 08:44
> This issue has me steering away from flowbite unfortunately.

From my experience of using Flowbite React adding `use client` would solve everything.

Interactive components are NOT supposed to be server components, as per the Next.js documentation.

I believe it's up to the developer to properly separate client and server components based on interactivity.

That being said, together with @tulup-conner we're planning on improving the examples based on the new docs redesign PR that we're working on quite a lot these past few weeks https://github.com/themesberg/flowbite-react/pull/642.

This PR should provide a much better SSC support for the currently existing examples.

Cheers,
Zoltan

**Comment by marcodenic** [comment] 2023-05-25 18:52
> @marcodenic do you know that flowbite-react is free, right?

yeah but I've been using the stuff for ages and we wanted access to the full figma file too.

but just discovered it's all a bit problematic during implementation.

**Comment by rluders** [comment] 2023-05-25 19:15
@marcodenic well, right now most react libraries are having issues with SSC. I'm working in some idea to provide some support for it, but during my free time, that isn't a much. The project is open source, so... feel free to contribute and fix the problematic parts, it will be most than welcome.

**Comment by marcodenic** [comment] 2023-05-25 19:47
> @marcodenic well, right now most react libraries are having issues with SSC. I'm working in some idea to provide some support for it, but during my free time, that isn't  much. The project is open source, so... feel free to contribute and fix the problematic parts, it will be most than welcome.

it wasn't a slight, I paid because I love flowbite and wanted to use it and support it. ♥️

I'll still use it, I only need a few interactive components so I'll just roll my own for now until ssc stuff is done, just need to do a bit more code than anticipated.

**Comment by BanDroid** [comment] 2023-05-25 20:45
my solution to work on this is to create a file with `"use client";` headers and then `export * from "flowbite-react";`.

in this example i use nextjs `13.4.3`, flowbite `^1.6.5`, flowbite-react `^0.4.4`, and also using src and app routing.

{root}/src/flowbite-components.tsx (you could name the file whatever you want)
```tsx
"use client";
export * from "flowbite-react";
```

{root}/src/app/page.tsx
```tsx
import { Alert } from "@/flowbite-components"

export default function Home() {
  return <>
    <Alert color="info">
      <span>
        <span className="font-medium">
          Info alert!
        </span>
        {' '}Change a few things up and try submitting again.
      </span>
    </Alert>
  </>
}
```

**Comment by tulup-conner** [comment] 2023-05-26 02:32
@BanDroid That's actually not the worst solution... Nice. Regardless, we are well aware of this issue and have plans to resolve the core problem, which is that every component needlessly uses the client to support `theme={}` attribute. Coming soon.

**Comment by ozelen** [comment] 2023-06-14 04:47
`'use client'` is easy, but what if I want the content to appear in search engines, which is the whole point of using SSR/SSG?

**Comment by tulup-conner** [comment] 2023-06-20 21:05
@ozelen Please see the comment above - components needlessly use the client, which will be changed so you can render React Server Components with Flowbite React.

**Comment by nickjanssen** [comment] 2023-06-23 13:57
In order to get around the `You cannot dot into a client module from a server component.` error I'm re-exporting Accordion, Navbar etc as below:

```
"use client";

import * as Flowbite from "flowbite-react";
export * from "flowbite-react";

const { Title, Panel, Content } = Flowbite.Accordion;
export { Title as AccordionTitle, Panel as AccordionPanel, Content as AccordionContent };

const { Brand, Toggle, Collapse } = Flowbite.Navbar;
export { Brand as NavbarBrand, Toggle as NavbarToggle, Collapse as NavbarCollapse };
```

**Comment by esistgut** [comment] 2023-07-22 10:48
Is the "use client" everywhere the only supported way? This kind of defeats the point of server components

**Comment by tulup-conner** [comment] 2023-07-23 06:05
Yep. We are aware of that, it's just a workaround. Good news: this is the next thing on my docket and I expect to have something resembling a solution in August.

**Comment by tulup-conner** [comment] 2023-08-22 03:36
Hey all, I just opened up a discussion at #923 with a few possible solutions to this problem. 

I want to personally thank @BanDroid and @nickjanssen again for providing their solutions that already work!

Please check that discussion out and give a vote and/or comment on your favorite solution(s). And please let us know there, too, if you have any ideas we didn't present.

**Comment by rluders** [comment] 2023-10-11 07:22
Folks,

Please test the [0.7.0-beta.2](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.2) release. It introduces some RSC support and improves the theme by converting it from Context to Singleton.

It shouldn't introduce any breaking change. If you find any issues, please, report them as an issue, and don't forget to say that you are using the beta version.

**Comment by SutuSebastian** [comment] 2023-10-13 11:15
> Folks,
> 
> Please test the [0.7.0-beta.2](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.2) release. It introduces some RSC support and improves the theme by converting it from Context to Singleton.
> 
> It shouldn't introduce any breaking change. If you find any issues, please, report them as an issue, and don't forget to say that you are using the beta version.

Update: small patch for the imports failing [0.7.0-beta.3](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.3)

**Comment by SutuSebastian** [comment] 2023-10-20 12:23
Update: [0.7.0-beta.4](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.4) is out, bringing even more RSC support for the following components:

1. Accordion
2. Dropdown
3. Navbar
4. Rating
5. Sidebar
6. Table
7. Timeline
8. Toast

**Comment by pangolingo** [comment] 2023-10-20 15:09
> Update: [0.7.0-beta.4](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.4) is out, bringing even more RSC support for the following components:

Some feedback on this beta (LMK if this issue isn't the best place for this feedback).

Here's the version in my `package.json`: `"flowbite-react": "0.7.0-beta.4",`

## When I import the sidebar components from `flowbite-react` I get an error 

> Error: Unsupported Server Component type: undefined

I can work around this by importing components from a subdirectory:

```javascript
import {
  Sidebar,
  SidebarItem,
  SidebarItemGroup,
  SidebarItems,
} from "flowbite-react/lib/esm/components/Sidebar";
```

## I get an error when using SidebarItem

```
import {
  SidebarItem,
} from "flowbite-react/lib/esm/components/Sidebar";
```

> Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> Check the render method of `Sidebar.Item`.

**Comment by SutuSebastian** [comment] 2023-11-12 09:18
> > Update: [0.7.0-beta.4](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.4) is out, bringing even more RSC support for the following components:
> 
> Some feedback on this beta (LMK if this issue isn't the best place for this feedback).
> 
> Here's the version in my `package.json`: `"flowbite-react": "0.7.0-beta.4",`
> 
> ## When I import the sidebar components from `flowbite-react` I get an error
> > Error: Unsupported Server Component type: undefined
> 
> I can work around this by importing components from a subdirectory:
> 
> ```js
> import {
>   Sidebar,
>   SidebarItem,
>   SidebarItemGroup,
>   SidebarItems,
> } from "flowbite-react/lib/esm/components/Sidebar";
> ```
> 
> ## ~I get an error when using SidebarItem~
> ## Correction: I get an error when I use SidebarItem as a Nextjs link
> ```
> import {
>   SidebarItem,
> } from "flowbite-react/lib/esm/components/Sidebar";
> ```
> 
> > Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
> > Check the render method of `Sidebar.Item`.
> 
> ```
> <SidebarItem as={Link} href="/">
>             <p>Overview</p>
>           </SidebarItem>
> ```

Should be fixed in  [0.7.0-beta.5](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.5).

**Comment by SutuSebastian** [comment] 2023-11-12 09:19
Update: [0.7.0-beta.5](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.5) brings full RSC support for all `flowbite-react` components 🔥

**Comment by h36ahmed** [comment] 2023-11-19 21:38
Seems like I am running into an issue with FloatingLabel using pnpm on Next.js - getting the following error - 
<img width="1008" alt="image" src="https://github.com/themesberg/flowbite-react/assets/13081913/e921e702-c5aa-4763-a92f-aa1f83a05ab9">

I am using the latest beta of flowbite

```
<FloatingLabel
      color={validationError ? 'error' : 'gray'}
      helperText={validationMessage}
      id={name}
      label={label}
      name={name}
      onChange={handleChange}
      placeholder={placeholder}
      required
      sizing="sm"
      theme={customTheme}
      type={type}
      value={value}
      variant="default"
    />
```

**Comment by BanDroid** [comment] 2023-11-20 09:54
> Update: [0.7.0-beta.5](https://www.npmjs.com/package/flowbite-react/v/0.7.0-beta.5) brings full RSC support for all `flowbite-react` components 🔥

hi, just want to notice.

please dont rely on sharp as dependency, it is not working in termux for android users. i cant use flowbite 0.7.0-beta.5 because sharp also rely on libvips natively, what kind of css library relying on native libraries?

**Closed** 2023-11-26 20:32 UTC
Labels: :bug: bug, confirmed, nextjs, workaround
