### ISSUE TITLE
(docs) wrong example code about navbar

### ISSUE THREAD

**Issue by himprover** [themesberg/flowbite-react#920] opened 2023-08-20 08:20 UTC
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Steps to reproduce

1. Go to [NavBar Component Docs](https://www.flowbite-react.com/docs/components/navbar)
2. Scroll down to **Navbar with dropdown**
3. Click to **Expand Code**

## Current behavior

```
<Dropdown
          inline
          label={<Avatar alt="User settings" img="https://flowbite.com/docs/images/people/profile-picture-5.jpg" rounded/>}
        >
          <Dropdown.Header>
            <span className="block text-sm">
              Bonnie Green
            </span>
            <span className="block truncate text-sm font-medium">
              name@flowbite.com
            </span>
          </Dropdown.Header>
          <Item>
            Dashboard
          </Item>
          <Item>
            Settings
          </Item>
          <Item>
            Earnings
          </Item>
          <Dropdown.Divider />
          <Item>
            Sign out
          </Item>
        </Dropdown>
```

## Expected behavior

```
<Dropdown
          inline
          label={<Avatar alt="User settings" img="https://flowbite.com/docs/images/people/profile-picture-5.jpg" rounded/>}
        >
          <Dropdown.Header>
            <span className="block text-sm">
              Bonnie Green
            </span>
            <span className="block truncate text-sm font-medium">
              name@flowbite.com
            </span>
          </Dropdown.Header>
          <Dropdown.Item>
            Dashboard
          </Dropdown.Item>
          <Dropdown.Item>
            Settings
          </Dropdown.Item>
          <Dropdown.Item>
            Earnings
          </Dropdown.Item>
          <Dropdown.Divider />
          <Dropdown.Item>
            Sign out
          </Dropdown.Item>
        </Dropdown>
```

## Context

It should be `<Dropdown.Item>`, but it's `<Item>`

When I first saw this issue, I was going to contribute that.

But, when I forked the repository, the code was written correctly `<Dropdown.Item>` (`app/docs/components/navbar/navbar.mdx`)

It needs check something to make it look right.

**Comment by tulup-conner** [comment] 2023-08-21 20:59
Thanks for submitting - this is a duplicate of #894 though. You can search the Issues by the label `Documentation` to more easily find this. It's not an issue with the `Navbar`, but the `Dropdown`.

**Closed by tulup-conner** 2023-08-21 20:59 UTC
